pullRequestOpened: >
  :wave: Thanks for creating a PR! <br />

  Before we can merge this PR, please make sure that all the following items have been 
  checked off. If any of the checklist items are not applicable, please leave them but
  write a little note why.   

  - [ ] Wrote tests <br /> 
  - [ ] Updated CHANGELOG_PENDING.md <br />  
  - [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work <br />
  - [ ] Updated relevant documentation (`docs/`) and code comments <br />
  - [ ] Re-reviewed `Files changed` in the Github PR explorer <br />
  - [ ] Applied Appropriate Labels  <br />

  <br />

  Thank you for your contribution to Tendermint! :rocket:   