coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 1%
    patch: on
    changes: off

github_checks:
  annotations: false

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "docs"
  - "DOCKER"
  - "scripts"
  - "**/*.pb.go"
  - "libs/pubsub/query/query.peg.go"
