pull_request_rules:
  - name: Automerge to master
    conditions:
      - base=master
      - label=S:automerge
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
  - name: backport patches to v0.34.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
