queue_rules:
  - name: default
    conditions:
      - base=master
      - label=S:automerge

pull_request_rules:
  - name: Automerge to master
    conditions:
      - base=master
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message: title+body
