queue_rules:
  - name: default
    conditions:
      - base=v0.35.x
      - label=S:automerge

pull_request_rules:
  - name: Automerge to v0.35.x
    conditions:
      - base=v0.35.x
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
<<<<<<< HEAD
        commit_message: title+body
=======
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: backport patches to v0.34.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
  - name: backport patches to v0.35.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.35.x
    actions:
      backport:
        branches:
          - v0.35.x
>>>>>>> 02d456b8b (Update Mergify configuration. (#7388))
