queue_rules:
  - name: default
    conditions:
      - base=master
      - label=S:automerge

pull_request_rules:
  - name: Automerge to master
    conditions:
      - base=master
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: backport patches to v0.34.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
  - name: backport patches to v0.35.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.35.x
    actions:
      backport:
        branches:
          - v0.35.x
  - name: backport patches to v0.36.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.36.x
    actions:
      backport:
        branches:
          - v0.36.x
