queue_rules:
  - name: default
    conditions:
      - base=master
      - label=S:automerge

pull_request_rules:
  - name: Automerge to master
    conditions:
      - base=master
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message: title+body
  - name: backport patches to v0.34.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
<<<<<<< HEAD
=======
  - name: backport patches to v0.35.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.35.x
    actions:
      backport:
        branches:
          - v0.35.x
>>>>>>> 2d4844f97 (Update mergify configuration. (#7385))
