queue_rules:
  - name: default
    conditions:
      - base=v0.35.x
      - label=S:automerge

pull_request_rules:
  - name: Automerge to v0.35.x
    conditions:
      - base=v0.35.x
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message: title+body
