linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    # - lll
    # - maligned
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - varcheck
    # - whitespace
    # - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  misspell:
    locale: US
