run:
  deadline: 1m

linters:
  enable-all: true
  disable:
    - gocyclo
    - golint
    - errcheck
    - unparam
    - lll
    - gochecknoglobals
    - gochecknoinits
    - stylecheck
    - funlen
    - godox
    - whitespace

linters-settings:
  dogsled:
    max-blank-identifiers: 3
