# .goreleaser.yml
builds:
  -
    id: "Tendermint"
    main: ./cmd/tendermint/main.go
    ldflags:
     - -s -w -X github.com/tendermint/tendermint/version.GitCommit={{.Commit }} -X github.com/tendermint/tendermint/version.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256
release:
  name_template: "{{.ProjectName}} {{.Version}}"
