pull_request_rules:
  - name: automerge to master with label S:automerge and branch protection passing
    conditions:
      - base=master
      - label=S:automerge
    actions:
      merge:
        method: squash
        strict: true
