// generated by stringer -type=RetCode; DO NOT EDIT

package types

import "fmt"

const _RetCode_name = "RetCodeOKRetCodeInternalErrorRetCodeUnauthorizedRetCodeInsufficientFeesRetCodeUnknownRequest"

var _RetCode_index = [...]uint8{0, 9, 29, 48, 71, 92}

func (i RetCode) String() string {
	if i < 0 || i+1 >= RetCode(len(_RetCode_index)) {
		return fmt.Sprintf("RetCode(%d)", i)
	}
	return _RetCode_name[_RetCode_index[i]:_RetCode_index[i+1]]
}
