FROM golang:latest

RUN mkdir -p /go/src/github.com/tendermint/tools/tm-bench
WORKDIR /go/src/github.com/tendermint/tools/tm-bench

COPY Makefile /go/src/github.com/tendermint/tools/tm-bench/

RUN make get_tools

COPY Gopkg.toml /go/src/github.com/tendermint/tools/tm-bench/
COPY Gopkg.lock /go/src/github.com/tendermint/tools/tm-bench/

RUN make get_vendor_deps

COPY . /go/src/github.com/tendermint/tools/tm-bench
