FROM golang:latest

RUN mkdir -p /go/src/github.com/tendermint/tools/tm-bench
WORKDIR /go/src/github.com/tendermint/tools/tm-bench

COPY Makefile /go/src/github.com/tendermint/tools/tm-bench/
COPY glide.yaml /go/src/github.com/tendermint/tools/tm-bench/
COPY glide.lock /go/src/github.com/tendermint/tools/tm-bench/

RUN make get_deps

COPY . /go/src/github.com/tendermint/tools/tm-bench
