// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	block "github.com/tendermint/tendermint/pkg/block"

	metadata "github.com/tendermint/tendermint/pkg/metadata"

	mock "github.com/stretchr/testify/mock"
)

// BlockStore is an autogenerated mock type for the BlockStore type
type BlockStore struct {
	mock.Mock
}

// Height provides a mock function with given fields:
func (_m *BlockStore) Height() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// LoadBlockCommit provides a mock function with given fields: height
func (_m *BlockStore) LoadBlockCommit(height int64) *metadata.Commit {
	ret := _m.Called(height)

	var r0 *metadata.Commit
	if rf, ok := ret.Get(0).(func(int64) *metadata.Commit); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.Commit)
		}
	}

	return r0
}

// LoadBlockMeta provides a mock function with given fields: height
func (_m *BlockStore) LoadBlockMeta(height int64) *block.BlockMeta {
	ret := _m.Called(height)

	var r0 *block.BlockMeta
	if rf, ok := ret.Get(0).(func(int64) *block.BlockMeta); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*block.BlockMeta)
		}
	}

	return r0
}
