# Runs randomly generated E2E testnets nightly.
name: e2e-nightly
on:
  workflow_dispatch: # allow running workflow manually
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  e2e-nightly-test-release:
    # Run parallel jobs for the listed testnet groups (must match the
    # ./build/generator -g flag)
    strategy:
      fail-fast: false
      matrix:
        group: ['00', '01', '02', '03']
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2
        with:
          ref: 'v0.34.x'

      - name: Build
        run: git branch
      #   working-directory: test/e2e
      #   # Run make jobs in parallel, since we can't run steps in parallel.
      #   run: make -j2 docker generator runner

      # - name: Generate testnets
      #   working-directory: test/e2e
      #   # When changing -g, also change the matrix groups above
      #   run: ./build/generator -g 4 -d networks/nightly

      # - name: Run testnets in group ${{ matrix.group }}
      #   working-directory: test/e2e
      #   run: ./run-multiple.sh networks/nightly/*-group${{ matrix.group }}-*.toml
